# Generated by Django 4.1.2 on 2022-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_perfil_status_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='resp',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tipo',
            field=models.CharField(choices=[('Materiais', 'materiais'), ('Animais', 'animais'), ('Ambos', 'ambos')], default='materiais', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='cns',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
