# Generated by Django 4.1.2 on 2022-10-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_formulario_resp_formulario_tipo_alter_formulario_cns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='resp',
            new_name='responsavel',
        ),
    ]
