# Generated by Django 4.1.2 on 2022-11-01 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0005_alter_perfil_fone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('data_observacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('formulario_observacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.formulario')),
                ('usuario_observacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
