# Generated by Django 4.1.3 on 2022-11-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_formulario_ni'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='caps',
            field=models.BooleanField(default=False, verbose_name='CAPS AD'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='caps_a',
            field=models.BooleanField(default=False, verbose_name='CAPS ADULTO'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='caps_i',
            field=models.BooleanField(default=False, verbose_name='CAPS IJ'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='cd_d',
            field=models.BooleanField(default=False, verbose_name='CD - Centro Dia'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='cer',
            field=models.BooleanField(default=False, verbose_name='CER'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='cras',
            field=models.BooleanField(default=False, verbose_name='CRAS'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='creas',
            field=models.BooleanField(default=False, verbose_name='CREAS'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dvz',
            field=models.BooleanField(default=False, verbose_name='DVZ'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='emad',
            field=models.BooleanField(default=False, verbose_name='EMAD'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='esf',
            field=models.BooleanField(default=False, verbose_name='ESF'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='esf_c',
            field=models.BooleanField(default=False, verbose_name='ESF-CNR'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='mp_gecap',
            field=models.BooleanField(default=False, verbose_name='MP–GECAP'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='mp_idoso',
            field=models.BooleanField(default=False, verbose_name='MP-PJDH-Idoso'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='mp_is',
            field=models.BooleanField(default=False, verbose_name='MP-PJDH-IS'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='mp_pd',
            field=models.BooleanField(default=False, verbose_name='MP-PJDH-PD'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='mp_sp',
            field=models.BooleanField(default=False, verbose_name='MP-PJDH-SP'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nasf',
            field=models.BooleanField(default=False, verbose_name='NASF'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nci',
            field=models.BooleanField(default=False, verbose_name='NCI'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nir',
            field=models.BooleanField(default=False, verbose_name='NIR'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='npj',
            field=models.BooleanField(default=False, verbose_name='NPJ'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='pai',
            field=models.BooleanField(default=False, verbose_name='PAI'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='pavs',
            field=models.BooleanField(default=False, verbose_name='PAVS'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='sad',
            field=models.BooleanField(default=False, verbose_name='SAD'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='sasf',
            field=models.BooleanField(default=False, verbose_name='SASF'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='ubs',
            field=models.BooleanField(default=False, verbose_name='UBS'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='ursi',
            field=models.BooleanField(default=False, verbose_name='URSI'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='uvis',
            field=models.BooleanField(default=False, verbose_name='UVIS'),
        ),
    ]
