# Generated by Django 4.1.3 on 2022-11-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_formulario_caps_formulario_caps_a_formulario_caps_i_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='caps',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='caps_a',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='caps_i',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='cd_d',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='cer',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='cras',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='creas',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='dvz',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='emad',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='esf',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='esf_c',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='mp_gecap',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='mp_idoso',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='mp_is',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='mp_pd',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='mp_sp',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nasf',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nci',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nir',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='npj',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='pai',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='pavs',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='sad',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='sasf',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='ubs',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='ursi',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='uvis',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='cns',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='OrgaosAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caps', models.BooleanField(default=False, verbose_name='CAPS AD')),
                ('caps_a', models.BooleanField(default=False, verbose_name='CAPS ADULTO')),
                ('caps_i', models.BooleanField(default=False, verbose_name='CAPS IJ')),
                ('cer', models.BooleanField(default=False, verbose_name='CER')),
                ('nir', models.BooleanField(default=False, verbose_name='NIR')),
                ('ubs', models.BooleanField(default=False, verbose_name='UBS')),
                ('ursi', models.BooleanField(default=False, verbose_name='URSI')),
                ('sad', models.BooleanField(default=False, verbose_name='SAD')),
                ('emad', models.BooleanField(default=False, verbose_name='EMAD')),
                ('pai', models.BooleanField(default=False, verbose_name='PAI')),
                ('pavs', models.BooleanField(default=False, verbose_name='PAVS')),
                ('esf_c', models.BooleanField(default=False, verbose_name='ESF-CNR')),
                ('esf', models.BooleanField(default=False, verbose_name='ESF')),
                ('nasf', models.BooleanField(default=False, verbose_name='NASF')),
                ('uvis', models.BooleanField(default=False, verbose_name='UVIS')),
                ('dvz', models.BooleanField(default=False, verbose_name='DVZ')),
                ('cras', models.BooleanField(default=False, verbose_name='CRAS')),
                ('creas', models.BooleanField(default=False, verbose_name='CREAS')),
                ('sasf', models.BooleanField(default=False, verbose_name='SASF')),
                ('cd_d', models.BooleanField(default=False, verbose_name='CD - Centro Dia')),
                ('npj', models.BooleanField(default=False, verbose_name='NPJ')),
                ('nci', models.BooleanField(default=False, verbose_name='NCI')),
                ('mp_idoso', models.BooleanField(default=False, verbose_name='MP-PJDH-Idoso')),
                ('mp_is', models.BooleanField(default=False, verbose_name='MP-PJDH-IS')),
                ('mp_pd', models.BooleanField(default=False, verbose_name='MP-PJDH-PD')),
                ('mp_sp', models.BooleanField(default=False, verbose_name='MP-PJDH-SP')),
                ('mp_gecap', models.BooleanField(default=False, verbose_name='MP–GECAP')),
                ('outros', models.CharField(blank='True', max_length=40, verbose_name='Outros Orgãos')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.formulario')),
            ],
        ),
    ]
