# Generated by Django 4.1.3 on 2022-11-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_formulario_orgaos_formulario_outros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fone',
            field=models.CharField(max_length=15),
        ),
    ]
