# Generated by Django 4.1.3 on 2022-11-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_perfil_fone'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nivel_acesso',
            field=models.CharField(choices=[('Crasa', 'crasa'), ('Supervisão', 'supervisao'), ('Unidade', 'unidade'), ('Usuario', 'usuario   '), ('Inativo', 'inativo')], default='inativo', max_length=16),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fone',
            field=models.CharField(max_length=14),
        ),
    ]
