# Generated by Django 4.1.3 on 2022-11-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_perfil_nivel_acesso_alter_perfil_fone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nivel_acesso',
            field=models.CharField(choices=[('crasa', 'Crasa'), ('supervisao', 'Supervisão'), ('unidade', 'Unidade'), ('usuario', 'Usuario'), ('inativo', 'Inativo')], default='inativo', max_length=16),
        ),
    ]
