# Generated by Django 4.1.3 on 2022-12-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_alter_perfil_nivel_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='cns',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CNS'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='complemento',
            field=models.CharField(blank='True', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
