# Generated by Django 4.1.3 on 2022-12-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_alter_formulario_cns_alter_formulario_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='cnsnaoinformado',
            field=models.CharField(blank=True, choices=[('Pessoa Acidentada Grave', 'Nao Informado'), ('Criança não possui', 'Nao Informado'), ('Pessoa se recusa fornecer', 'Nao Informado'), ('Pessoa com Condição CLinica ou Neurologica Grave', 'Nao Informado'), ('Pessoa Estrangeira', 'Nao Informado'), ('Pessoa com Transtorno Mental', 'Nao Informado')], max_length=60, null=True),
        ),
    ]
