# Generated by Django 4.1.4 on 2022-12-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_remove_formulario_log_formulario_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='cnsnaoinformado',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='outros',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='prefeitura',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='supervisao',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='complemento',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='cor',
            field=models.CharField(choices=[('Branca', 'branca'), ('Parda', 'parda'), ('Preta', 'preta'), ('Amarela', 'amarela'), ('Indigena', 'indigena'), ('ni', 'nao informado')], default=None, max_length=10),
        ),
    ]
