# Generated by Django 4.1.4 on 2022-12-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_remove_formulario_cnsnaoinformado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='cnsnaoinformado',
            field=models.CharField(blank=True, choices=[('Nao Informado', 'Pessoa Acidentada Grave'), ('Nao Informado', 'Criança não possui'), ('Nao Informado', 'Pessoa se recusa fornecer'), ('Nao Informado', 'Pessoa com Condição CLinica ou Neurologica Grave'), ('Nao Informado', 'Pessoa Estrangeira'), ('Nao Informado', 'Pessoa com Transtorno Mental')], max_length=60, null=True, verbose_name='CNS Não Informado'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='cep',
            field=models.CharField(max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
