# Generated by Django 4.1.4 on 2022-12-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_formulario_cnsnaoinformado_alter_formulario_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='outros',
            field=models.CharField(blank='True', max_length=40, verbose_name='Outros Orgãos'),
        ),
    ]
