# Generated by Django 4.1.2 on 2022-10-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisao',
            name='prefeitura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidade.prefeitura'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='supervisao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidade.supervisao'),
        ),
    ]
